### ISSUE TITLE
Allow empty packages argument

### ISSUE THREAD

**Issue by tueda** [awalsh128/cache-apt-pkgs-action#149]
I would like to use `cache-apt-pkgs-action` like this:
```
    - name: Install optional dependencies/tools
      uses: awalsh128/cache-apt-pkgs-action@v1
      with:
        packages: >-
          ${{ steps.setup.outputs.coverage == 'true' && 'lcov' || '' }}
          ${{ steps.setup.outputs.doxygen == 'true' && 'doxygen' || '' }}
          ${{ steps.setup.outputs.mpfr == 'true' && 'libmpfr-dev' || '' }}
          ${{ steps.setup.outputs.valgrind == 'true' && 'valgrind' || '' }}
        version: 1.0
```
to install optional packages, which are dynamically determined within the workflow (e.g., based on `matrix`). However, if none of the packages are enabled, the action fails with an error: `Packages argument cannot be empty`.

While this can be worked around by using a shell script to construct the package list and check if it is empty or by adding an `if:` condition to check whether any packages are enabled, it might be useful for `cache-apt-pkgs-action` to support an empty `packages` argument (simply doing nothing in this case).

For example, similar to [`actions/upload-artifact`](https://github.com/actions/upload-artifact)'s `if-no-files-found`, an `if-packages-empty` option (`error` (default), `warn`, `ignore`) would be useful.

**Comment by awalsh128** [comment]
Hi @tueda, could you add this feature to the action flags? My workload has been pretty heavy and it has been difficult to get around to these enhancements in a timely manner.

**Comment by echedey-ls** [comment]
I think this issue is now resolved and can be safely closed.

**Comment by tueda** [comment]
Actually, this option is still not available for `@latest` and `@v1`, is it?
